### ISSUE TITLE
Missing implementation of ComboBox

### ISSUE THREAD

**Issue by safibarri** [m-m-m/ui-fx#11]
when using UiComboBox and running the Ui-fx application 
an IllegalArgumentException is thrown which as per @hohwille  means that the ComboBox isn't implemented.

**Comment by hohwille** [comment]
JavaFx ComboBox does not support autocompletion out of the box. What a pitty.
I started implementing this manually. It paritally works but is still quite buggy. Especially I am struggling with this issue:
https://bugs.openjdk.java.net/browse/JDK-8088974

**Comment by hohwille** [comment]
I finally managed to fix the bugs. The only remaining problem is that the drop-down heigth does not properly resize while editing the filter inside the `ComboBox` resulting in the situation that you can not see the additional options. In the worst case the heigth only shows one item and even when deleting the filter text and restoring all options you visually can only see one of them and do not get that you also have all the other options. IMHO a bug of JavaFx but this project is not really active anymore and tries to reject as much bugs as possible. Therefore I will continue to find a workaround that would trigger the `ComboBox` to reopen/rerender the drop-down.

**Comment by hohwille** [comment]
Created issue #13, closing this issue now.
